server:
  port: 9090

auth:
  secret-key: gpBKq8

spring:
  application:
    name: zenprint-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/zenprint?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: sg3plcpnl0223.prod.sin3.secureserver.net
    port: 465
    username: info@autocinclus.com
    password: R@ymond13ize
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.ssl.enable": true

logging:
  level:
    root: INFO

log:
  pattern: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %5p ${PID} [%t] [%logger{0}] - %msg%n"
  path: out/logs/zenprint.log
  before-request-prefix: "Before Request:"
  after-request-prefix: "After Request:"
  after-response-prefix: "Response:"

cors:
  urls: '*'
  origin: '*'
  allowed:
    methods: GET,POST,PUT,PATCH,DELETE

file:
  path:
    shirt: "D://designs/shirt/"
    packaging: "D://designs/packaging/"
    sticker: "D://designs/sticker/"