server:
  port: 9090

auth:
  secret-key: gpBKq8

spring:
  application:
    name: zenprint-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/zenprint
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO

log:
  pattern: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %5p ${PID} [%t] [%logger{0}] - %msg%n"
  path: out\logs\zenprint.log
  before-request-prefix: "Before Request:"
  after-request-prefix: "After Request:"
  after-response-prefix: "Response:"

cors:
  urls: '*'
  origin: '*'
  allowed:
    methods: GET,POST,PUT,PATCH,DELETE